Add jobs to create docker image to docker hub

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -52,4 +52,39 @@ jobs:
             curl -v http://localhost:8080/utility/namespaces
             curl -v http://localhost:8080/utility/idp
             curl -v http://localhost:8080/utility/services
+  push_to_docker_hub:
+    docker:
+      - image: circleci/node:carbon
+    steps:
+      - checkout
+      - setup_remote_docker
+      - run:
+          name: Build docker images
+          command: |
+            cd docker
+            REPO_NAME=${REPO_NAME:-$DOCKER_USER}
+            DOCKER_TAG=${DOCKER_TAG:-latest}
+            ./build.sh
+      - run:
+          name: Push to docker hub
+          command: |
+            if [ ! "$DOCKER_USER"  -o  ! "$DOCKER_PASS"  ]
+            then
+              echo "Missing required environment variables"
+              echo "- DOCKER_USER"
+              echo "- DOCKER_PASS"
+              exit 1
+            fi
+            REPO_NAME=${REPO_NAME:-$DOCKER_USER}
+            DOCKER_TAG=${DOCKER_TAG:-latest}
+            docker login -u $DOCKER_USER -p $DOCKER_PASS
+            docker push $REPO_NAME/api:$DOCKER_TAG
 
+workflows:
+  version: 2
+  build_and_deploy:
+    jobs:
+      - build
+      - push_to_docker_hub:
+          requires:
+            - build
